version: "3"
   
services:
  app:
    build: ./app
    container_name: app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm start